name: Application CI

on:
  workflow_dispatch:
  pull_request:
  push:
    branches: main
    tags: ['*']

jobs:
  build:
    permissions:
      contents: write
      pages: write
      id-token: write
    uses: DreamWeave-MP/StroggForge/.github/workflows/rustGlobalBuild.yml@v39
    secrets: inherit
    with:
      binary_names: '["dream_archivetool"]'
      generate_benchmarks: true
      enable_android: true
      enable_portmaster: true
